# PK/PD equations


formSS3<-"dose * (KA/V * ((CLSE/V) - KA)/((((((ClS/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) - KA) * (((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) - KA)) * exp(-KA * (t - 0))/(1 - exp(-KA * 24)) + KA/V * ((CLSE/V) - ((((ClS/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2))/((KA - ((((ClS/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2)) * (((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) - ((((ClS/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2))) * exp(-((((ClS/V) + 
(CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) * (t - 0))/(1 - exp(-((((ClS/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) * 24)) + KA/V * ((CLSE/V) - ((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2))/((KA - ((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2)) * (((((ClS/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) - ((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2))) * exp(-((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) * (t - 
0))/(1 - exp(-((((ClS/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS/V) * (CLSE/V)))/2) * 24)))" 
###one group 5 samp times

formSS3_cov<-"36 * (KA/V * ((CLSE/V) - KA)/((((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) - KA) * (((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) - KA)) * exp(-KA * (t - 0))/(1 - exp(-KA * 24)) + KA/V * ((CLSE/V) - ((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2))/((KA - ((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2)) * (((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) - ((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2))) * exp(-((((ClS*exp(BETA*dose)/V) + 
(CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) * (t - 0))/(1 - exp(-((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) * 24)) + KA/V * ((CLSE/V) - ((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2))/((KA - ((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2)) * (((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) + sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) - ((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2))) * exp(-((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) * (t - 
0))/(1 - exp(-((((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5)) - sqrt(((ClS*exp(BETA*dose)/V) + (CLSE/V) + (CLES/57.5))**2 - 4 * (ClS*exp(BETA*dose)/V) * (CLSE/V)))/2) * 24)))" 
